dist: trusty
chrome: stable
language: node_js
node_js:
- "9"

branches:
  only:
    - master

script:
  - npm run build:lib
  - npm run test:lib --watch=false --browsers=ChromeHeadless

before_deploy:  
  - cd dist/core

deploy:
  provider: npm
  email: chihab@gmail.com
  skip_cleanup: true
  api_key:
    secure: OTwaO9DhLeKx/sVm+sj9aFRoXs9aAyNlNJLFuH4vUByijaK6ndwYjkwz2tlSOjxtJ9KZUbQ3vSYLx5GUo1tr8+RZR01Wahje0vqeBhlatC2Mnd4+N2au7ftGTU+d0Ve9BCJByyJ4EuYkoedmgcwuqUucki9OqXrmtSoTFYJml8+ysO9I6bxThSALHJ3XrifMp+FvUBDNse6fJmyuEQW7qWUMvkPnMVmJnyriRVLhvXJ5sWIr5buN3zZjUm4zU7YB1HewAhKivdD5tqe1vey5K2nwuH7CSwS/OTipqKXFcli2ecIOz9d8FD5LwZaRyzCrA1UBLsD4GuJ8mCDwzhAE7VLXQ7RyzYIyLIJ93kwA5ceP/9HRiJ6BfyGgg/7hBSAdawScPz68PbEpsW2JGmTl0iy/GsxbfUoAa+RFvfSolMMx3/nrJ96gvZYzmWwDPT6ZTic/x4NQSow6z40uhdQtyx0I8TxtZ2J7dBUiQE2h40NLSeFALnIhpGmOA/7epRgICGGL9C+ymFHfsd4Dt5h6+CQm6Sql7YMfzhKPUtMxg8AjS7D/2I6UFbVwd6/uWfvM9iwhqJZ/HsKHruTx6N2oeiiTuUAcz38rrc/0drXJPt+e18oZTeywGB4UKJ/0UcL+BiQZ63jshp16Y+u8HXe3qCPQoLqk6Py5wwNRCu6w3Ks=
  on:
    branch: master
    repo: chihab/ngx-access
