name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]
        angular-version:
          [
            6.0.x,
            6.1.x,
            7.0.x,
            7.1.x,
            7.2.x,
            8.0.x,
            8.1.x,
            8.2.x,
            9.0.x,
            9.1.x,
            10.0.x,
            10.1.x,
            10.2.x,
            11.0.x,
            11.1.x,
            11.2.x,
          ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use Angular ${{ matrix.angular-version }}
        uses: ngworker/angular-versions-action@v1
        with:
          angular-version: ${{ matrix.angular-version }}

      - run: yarn install
      - run: yarn lint
      - run: yarn build
      - run: yarn test
